<a href="https://colab.research.google.com/github/LuanaGoncalves177/Linguagem_Python_Colab/blob/main/Python_An%C3%A1lise_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Análise de dados com Python
#1 Passo a passo do projeto
  # 1. Abri a base de dados (importar a base de dados);
    #pandas: pip install pandas openpyxl nbformat ipykernel plotly

import pandas as pd

tabela = pd.read_csv("cancelamentos.csv")

#print(tabela) imprimi a tabele desformatada

display(tabela)
  # 2. Visualizar a base de dados;
    # 2.1 entender as informações disponíveis;
    # 2.2 possívesis erros na base de dados;
    # 2.3 informações que não ajudam  que atrapalham
    # lista_nomes = ["lira", "talia"] criação de lista em python

print("Tabela limpa.")
tabela = tabela.drop(columns="CustomerID")
display(tabela)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

Tabela limpa.

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [ ]:
# 3.corrigir os prolemas da base de dados; (tratamentos de dados)
display(tabela.info())
  # 3.1 valores em formatos errados

  # 3.2 Informações vazias (Excluir informações)
print("Tabela limpa!")
tabela = tabela.dropna()
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   50000 non-null  float64
 1   sexo                    49997 non-null  object
 2   tempo_como_cliente      49998 non-null  float64
 3   frequencia_uso          50000 non-null  float64
 4   ligacoes_callcenter     50000 non-null  float64
 5   dias_atraso             50000 non-null  float64
 6   assinatura              50000 non-null  object
 7   duracao_contrato        50000 non-null  object
 8   total_gasto             50000 non-null  float64
 9   meses_ultima_interacao  50000 non-null  float64
 10  cancelou                50000 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.2+ MB

None

Tabela limpa!
<class 'pandas.core.frame.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  object
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  object
 7   duracao_contrato        49996 non-null  object
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.6+ MB

None

In [ ]:
# 4. Análise inicial(entender o motivo do cancelamentos);
# 4.1 Quantidade
#contar quantos cara são 0 e 1 na coluna Candelou

print("Valores brutos cancelados")
display(tabela["cancelou"].value_counts())
#display(tabela["duracao_contrato"].value_counts()) - quantidade os planos

# 4.2 Porcentagem
print("Valores em percentuais")
display(tabela["cancelou"].value_counts(normalize=True))
#display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format)) formatar casas decimais

Valores brutos cancelados

cancelou
1.0    28393
0.0    21603
Name: count, dtype: int64

Valores em percentuais

cancelou
1.0    0.567905
0.0    0.432095
Name: proportion, dtype: float64

In [ ]:
# 5. Análise detalhada para enter a causa do cancelamento dos clientes.
import plotly.express as px
print(tabela.columns) # printa as colunas da tabela

# 5.1 Cria o gráfico
for coluna in tabela.columns:
  grafico = px.histogram(tabela, x=coluna, color="cancelou",text_auto=True)
  # 5.2 Mostra o gráfico
  grafico.show()

In [ ]:
import pandas as pd

try:
    tabela = pd.read_csv("cancelamentos.csv")
except FileNotFoundError:
    print("Erro: O arquivo 'cancelamentos.csv' não foi encontrado. Por favor, certifique-se de que o arquivo está no diretório correto.")
    tabela = pd.DataFrame() # Create an empty DataFrame to prevent NameError

if not tabela.empty:
    tabela = tabela.drop(columns="CustomerID")
    tabela = tabela.dropna()

    # Conclusões das análises

    # Todo mundo o contrto mensal cancelou
      # Desconto do contrato anual ou trimestral

    #lgacões callceter acima de 4 todo mundo cancelou
      # Tem algum problema e não estamos conseguindo resolver
      # se o cliente ligar mais de 3X pro callcenter - alerta vermelho

    # Atraso no pagamento acima de 20 dias, o cliente cancela
      #Se o cliente atrazar 15 dias no pagemento - alerta vermelho

    #Filtrar a base de dados
    # cancelamento = 56%

    # duracao_contratos -> diferente do Monhly
    condicao = tabela["duracao_contrato"] != "Monthy"
    tabela = tabela[condicao]

    # ligacao_callcenter -> menores ou igual a 4 ligações
    condicao = tabela["ligacoes_callcenter"] <= 4
    tabela = tabela[condicao]

    # dias_atraso -> menores ou iguais a 20
    condicao = tabela["dias_atraso"] >= 20
    tabela = tabela[condicao]

    display(tabela["cancelou"].value_counts(normalize=True))
else:
    print("Não foi possível processar a tabela devido ao erro de carregamento do arquivo.")

cancelou
1.0    0.81779
0.0    0.18221
Name: proportion, dtype: float64